### ISSUE TITLE
Bug when parsing yaml

### ISSUE THREAD

**Issue by carvido1** [datreeio/datree#668]
**Describe the bug**

A bug was introduced on the [release 1.4.37](https://github.com/datreeio/datree/releases/tag/1.4.37). It seems the extractor component was changed on this release.

This is an error example

```bash
\ Loading... panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 41 [running]:
github.com/datreeio/datree/pkg/extractor.extractConfigurationK8sData({0xc0000fb500, 0x31c, 0x380})
	/home/travis/gopath/src/github.com/datreeio/datree/pkg/extractor/extractor.go:134 +0x2f4
github.com/datreeio/datree/pkg/extractor.extractYamlConfigurations({0xc00042e000, 0x4c65})
	/home/travis/gopath/src/github.com/datreeio/datree/pkg/extractor/extractor.go:114 +0x2ee
github.com/datreeio/datree/pkg/extractor.ParseYaml(...)
	/home/travis/gopath/src/github.com/datreeio/datree/pkg/extractor/extractor.go:79
github.com/datreeio/datree/pkg/extractor.ExtractConfigurationsFromYamlFile({0xc0000e0910, 0x4b})
	/home/travis/gopath/src/github.com/datreeio/datree/pkg/extractor/extractor.go:57 +0x289
github.com/datreeio/datree/bl/files.(*FilesExtractor).ExtractFilesConfigurations.func1.1()
	/home/travis/gopath/src/github.com/datreeio/datree/bl/files/files.go:43 +0xbf
created by github.com/datreeio/datree/bl/files.(*FilesExtractor).ExtractFilesConfigurations.func1
	/home/travis/gopath/src/github.com/datreeio/datree/bl/files/files.go:36 +0x65
```

**To Reproduce**

The ingress-nginx helm chart templates can be used as example to reproduce the bug:

Execute the following command using datree 1.4.37

```bash
helm template ingress-nginx/ingress-nginx --include-crds --version 4.0.15 -n ingress | yq | ~/Downloads/datree-cli_1.4.37_Darwin_x86_64/datree test -
\ Loading... panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 41 [running]:
github.com/datreeio/datree/pkg/extractor.extractConfigurationK8sData({0xc0000fb500, 0x31c, 0x380})
	/home/travis/gopath/src/github.com/datreeio/datree/pkg/extractor/extractor.go:134 +0x2f4
github.com/datreeio/datree/pkg/extractor.extractYamlConfigurations({0xc00042e000, 0x4c65})
	/home/travis/gopath/src/github.com/datreeio/datree/pkg/extractor/extractor.go:114 +0x2ee
github.com/datreeio/datree/pkg/extractor.ParseYaml(...)
	/home/travis/gopath/src/github.com/datreeio/datree/pkg/extractor/extractor.go:79
github.com/datreeio/datree/pkg/extractor.ExtractConfigurationsFromYamlFile({0xc0000e0910, 0x4b})
	/home/travis/gopath/src/github.com/datreeio/datree/pkg/extractor/extractor.go:57 +0x289
github.com/datreeio/datree/bl/files.(*FilesExtractor).ExtractFilesConfigurations.func1.1()
	/home/travis/gopath/src/github.com/datreeio/datree/bl/files/files.go:43 +0xbf
created by github.com/datreeio/datree/bl/files.(*FilesExtractor).ExtractFilesConfigurations.func1
	/home/travis/gopath/src/github.com/datreeio/datree/bl/files/files.go:36 +0x65
```

**Expected behavior**

I have checked and latest verision that works is datree 1.4.35, so we can use this release as expected behaviour:

```bash
helm template ingress-nginx/ingress-nginx --include-crds --version 4.0.15 -n ingress | yq | ~/Downloads/datree-cli_1.4.35_Darwin_x86_64/datree test -
Your CLI version is deprecated, please upgrade your CLI to avoid problems. Refer to our docs for version upgrade instructions - https://hub.datree.io/#1-install-the-datree-cli
>>  File: /var/folders/2b/skmk9lmd057dw525xnyj_hr40000gn/T/datree_temp_3334064916.yaml

[V] YAML validation
[X] Kubernetes schema validation

❌  k8s schema validation error: For field spec: Additional property ipFamilies is not allowed

❌  k8s schema validation error: For field spec: Additional property ipFamilyPolicy is not allowed


[?] Policy check didn't run for this file


(Summary)

- Passing YAML validation: 1/1

- Passing Kubernetes (1.19.0) schema validation: 0/1

- Passing policy check: 0/1

+-----------------------------------+------------------------------------------------------+
| Enabled rules in policy “Default” | 21                                                   |
| Configs tested against policy     | 0                                                    |
| Total rules evaluated             | 0                                                    |
| Total rules skipped               | 0                                                    |
| Total rules failed                | 0                                                    |
| Total rules passed                | 0                                                    |
| See all rules in policy           | https://app.datree.io/login?t=34J58APeap5utyPPvsuGif |
+-----------------------------------+------------------------------------------------------+

```

**Desktop (please complete the following information):**

 - OS: macOS Monterey 12.4 
 - CPU: 2,6 GHz 6-Core Intel Core i7

**Datree version:**

 - Version: > 1.4.37

**Client ID:**

 - client_id: t6SJxkv7zVfeThc8g3C4XH

**Comment by myishay** [comment]
@carvido1 I see the bug on our side, it is indeed due to the changes in version 1.4.37.
I will create a fix soon

**Comment by myishay** [comment]
Fix released  in https://github.com/datreeio/datree/releases/tag/1.5.2
@carvido1 thanks for the detailed report!
